# Generated by Django 2.2.24 on 2021-12-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projawards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
