# Generated by Django 2.2.24 on 2021-12-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projawards', '0002_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
