# Generated by Django 2.2.24 on 2021-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projawards', '0003_auto_20211212_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='1'),
        ),
    ]
